version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DATABASE_URL: postgresql://user:pass@db:333/floatdb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: floatdb
    ports:
      - "333:5432"
