version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DATABASE_URL: postgresql://user:pass@db:5432/floatdb  # Corrected DB port
      REDIS_URL: redis://redis:6379  # Include Redis URL for the backend
    networks:
      - float-net
    volumes:
      - ./backend/logs:/app/logs  # Optional: Persist backend logs

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - float-net

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Expose Redis on a non-default external port
    networks:
      - float-net
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: floatdb
    ports:
      - "333:5432"  # Expose PostgreSQL on port 333 externally
    networks:
      - float-net
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

networks:
  float-net:  # Custom Docker network for better isolation

volumes:
  db_data:  # Named volume for database persistence

